### PR TITLE
[i18n] Improvements of the German translation

### PR DESCRIPTION
**Pull request by rrunner64**
Fixed some typos and and made some changes to avoid misunderstandings.

### CODE REVIEW

**Comment by aebruno** [comment]
Thanks!

**Comment by rrunner64** [comment]
@aebruno: Your binary of release v0.4.1 still uses the old translations. When I look at the time stamps in the rpm file I can see that _whisperfish_de.qm_ is older than _whisperfish_de.ts_.

**Comment by aebruno** [comment]
@rrunner64 Yeah sorry about that! I noticed this right after I did the release. Forgot to re-compile the translations. It will be included in the next release. Going to add as part of the build to compile translations so this won't get missed again.

**Comment by aebruno** [comment]
This should be included in v0.4.2.

**Comment by rrunner64** [comment]
Thank you!

**Pull request merged**
