### PR TITLE
small fixes in German translation

### PR DESCRIPTION
**Pull request by slohse**
Some small fixes in the German translation:
* added a missing translation
* fixed incorrect phone number example (no leading zero in area code when there is a country code)
* small grammar fix

### CODE REVIEW

**Comment by bonanza123** [comment]
Can you also fix/check all other `<translation type="unfinished">` ? Most of them seem to be fine to me.

**Comment by slohse** [comment]
Yeah, I though so too, but I wasn't sure if there was some non-obvious meaning to them being marked as "unfinished".
I'll look them over

**Comment by slohse** [comment]
Okay, I went through all of them and they seem fine to me. I clarified the "scale JPEGs" one a bit, on all others I merely removed the `type="unfinished"` property.

**Comment by aebruno** [comment]
Thanks!

**Pull request merged**
